services:
  redis:
    image: redis/redis-stack:latest  
    container_name: redis 
    ports:
      - "6379:6379"
      - "8001:8001"  
    ulimits:
      memlock: -1 
    restart: unless-stopped
    networks:
      - hero_network

  app:
    image: hero0ncloud/leptos-portfolio-admin:v6
    container_name: leptos_portfolio_app
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - hero_network

networks:
  hero_network:
    driver: bridge
