version: "3.8"
services:
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly_redis 
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1 
    restart: unless-stopped
    networks:
      - hero_network

  app:
    image: hero0ncloud/leptos-portfolio-admin:v6
    container_name: leptos_portfolio_app
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - hero_network

networks:
  hero_network:
    driver: bridge
